### ISSUE TITLE
Infografía Roldan Uriel Arcadio Avila

### ISSUE THREAD

**Issue by roldanU** [SistemasTecTlaxiaco/infografia-de-hilos-roldanU#2]
![Roldan Uriel Arcadio Avila 4BS Infografia](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-roldanU/assets/163037330/e53aeb6c-be83-4cef-9cd8-15761850b402)

**Comment by Daniel-Velasco-Lopez** [comment]
En base a la rúbrica, has obtenido un 20% de 20%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
